name: Tweet

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  tweet:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "API_KEY_SECRET=${{ secrets.API_KEY_SECRET }}" >> $GITHUB_ENV
          echo "ACCESS=${{ secrets.ACCESS }}" >> $GITHUB_ENV
          echo "ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}" >> $GITHUB_ENV
      - run: npm i twitter-api-v2
      - run: node index.js