name: Tweet

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"

jobs:
  activate_deactivate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Set vars
        run: |
          echo "API_KEY=${{ vars.API_KEY }}" >> $GITHUB_ENV
          echo "API_KEY_SECRET=${{ vars.API_KEY_SECRET }}" >> $GITHUB_ENV
          echo "ACCESS=${{ vars.ACCESS }}" >> $GITHUB_ENV
          echo "ACCESS_SECRET=${{ vars.ACCESS_SECRET }}" >> $GITHUB_ENV
      - run: npm i twitter-api-v2
      - run: |
          cd ..
          ls
          echo 1
          cd ..
          ls
          echo 1
          cd ..
          ls
          echo 1
          cd ..
          ls
          echo 1
